version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
  - source: /scripts/
    destination: /home/ubuntu/scripts/
  - source: /bot/
    destination: /home/ubuntu/bot/
  - source: /bot/config/
    destination: /bot/config/
hooks:
  PreInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/post_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timemout: 300
      runas: root
