version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
  - source: /scripts/
    desitnation: /home/ubuntu/scripts
  - source: /bot/
    desitnation: /home/ubuntu/bot/
  - source: /bot/config/
    desitnation: /home/ubuntu/bot/config/
hooks:
  PreInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/post_install
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server
      timemout: 300
      runas: ubuntu
