version: 0.2
phases:
  install:
    commands:
      - apt-get update
      - command -v forever >/dev/null 2>&1 || { echo >&2 "Do not have forever install!"; exit 1; }
      - forever stopall
artifacts:
  files:
    - "**/*"
