version: 0.2
phases:
  install:
    commands:
      - apt-get update
artifacts:
  files:
    - "bot.js"
    - ideas.js
    - leaderboard.js
    - "package-lock.json"
    - "package.json"
    - "Channels.json"
    - "appspec.yml"
    - "scripts/*"
